apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  workspaces:
    - description: |
        This workspace is shared among all the pipeline tasks to read/write common resources
      name: source
  tasks:
    - name: build
      timeout: 30m
      retries: 0
      taskRef:
        resolver: katanomi.hub
        params:
          - name: kind
            value: task
          - name: name
            value: build-image-buildkit
      workspaces:
        - name: source
          workspace: source
        - name: cache
        - name: config
      when: []
      params:
        - name: container-images
          value:
            - 192.168.137.20:32222/simple-app/simple-app:$(build.git.branch.nameAsTag)-$(build.git.lastCommit.shortID)
        - name: extra-args
          value: --opt build-arg:BASE=192.168.137.20:32222/library/golang:1.16
    - name: deploy-test
      timeout: 30m
      retries: 0
      taskRef:
        resolver: katanomi.hub
        params:
          - name: kind
            value: task
          - name: name
            value: run-script
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - build
      when:
        - input: $(build.git.branch.name)
          operator: in
          values:
            - master
      params:
        - name: command
          value: |-
            echo "$(tasks.build.results.ociContainerImageBuild-url[0])"
            cd config/overlays/local
            kustomize edit set image simple-app=192.168.137.20:32222/simple-app/simple-app:$(build.git.branch.nameAsTag)-$(build.git.lastCommit.shortID)
            # kustomize edit set image simple-app=
            cd -

            kustomize build config/overlays/
  git:
    options:
      depth: 1
      timeout: 10m
      retries: 0
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
  runTemplate:
    spec:
      taskRunSpecs: []
